// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async loadAppState() : Promise<Result<PersistedAppState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_app_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveAppState(appState: PersistedAppState) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_app_state", { appState }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setHasUnsavedChanges(dirty: boolean) : Promise<void> {
    await TAURI_INVOKE("set_has_unsaved_changes", { dirty });
},
async hasUnsavedChanges() : Promise<boolean> {
    return await TAURI_INVOKE("has_unsaved_changes");
},
async logFrontendError(message: string, stack: string | null, componentStack: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_frontend_error", { message, stack, componentStack }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasRecentCrash() : Promise<Result<CrashReportSummary | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_recent_crash") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCrashReports() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_crash_reports") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCrashReport(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_crash_report", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearCrashReports() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_crash_reports") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async collectDiagnostics(tauriVersion: string) : Promise<Result<DiagnosticsReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collect_diagnostics", { tauriVersion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Registers `accelerator` for `purpose`, replacing whatever that purpose had
 * registered before. No-ops when the accelerator is already the current one.
 */
async registerGlobalShortcut(purpose: ShortcutPurpose, accelerator: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_global_shortcut", { purpose, accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Releases the accelerator held for `purpose`, if any.
 */
async unregisterGlobalShortcut(purpose: ShortcutPurpose) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unregister_global_shortcut", { purpose }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isGlobalShortcutRegistered(accelerator: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_global_shortcut_registered", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Quits for real, whatever the platform's close convention is.
 * 
 * On macOS the main window's close button only hides, so the Quit menu item
 * and the `app-quit` command need a path that actually ends the process. The
 * frontend flushes its stores before calling this.
 */
async quitApp() : Promise<void> {
    await TAURI_INVOKE("quit_app");
},
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openPreferencesFile() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_preferences_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Positions the pane on whichever monitor the cursor is on, then shows it.
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hides the pane.
 * 
 * Both the blur handler and the submit handler call this, and on some
 * platforms hiding triggers another blur, so the visibility guard keeps the
 * double call harmless.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cleanupOldRecoveryFiles() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Async so the first enumeration (~100ms of directory walking) never blocks
 * the main thread; later calls return the cached list.
 */
async listSystemFonts() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_system_fonts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reads a user-picked VS Code theme file for the import flow.
 * 
 * The template ships without `tauri-plugin-fs`, so this one narrow command
 * stands in for it: extension-pinned to theme JSON, size-capped, contents
 * returned as text for the frontend's JSONC parser to make sense of.
 */
async readThemeFile(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_theme_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppPreferences = { theme: string; lightProfile: ThemeProfile; darkProfile: ThemeProfile; importedThemes: ImportedTheme[]; 
/**
 * UI font family; `None` means the platform's system font stack.
 */
fontFamily: string | null; 
/**
 * Root font size in px. Rem-based sizing scales with it, so this acts
 * as an overall UI scale rather than a text-only size.
 */
fontSize: number; 
/**
 * `"system"`, `"on"`, or `"off"`.
 */
reducedMotion: string; 
/**
 * Web-style hand cursor over interactive elements instead of the
 * platform-native arrow.
 */
pointerCursors: boolean; 
/**
 * Native window translucency (Mica/Acrylic on Windows, vibrancy on
 * macOS) behind the app canvas. No effect on Linux.
 */
windowEffects: boolean; language: string | null; globalShortcut: string | null; quickPaneShortcut: string | null; 
/**
 * Per-command overrides for in-app shortcuts, keyed by command id.
 * A missing key means "use the command's built-in default"; an explicit
 * `None` means the user unbound the shortcut. Values are normalised
 * frontend combos (e.g. `"mod+shift+k"`), not Tauri accelerators.
 */
commandShortcuts: Partial<{ [key in string]: string | null }> }
export type CrashReportSummary = { filename: string; timestampSecs: number; secondsAgo: number }
export type DiagnosticsReport = { appName: string; appVersion: string; osName: string; osArch: string; osVersion: string; tauriVersion: string; settings: JsonValue; recentCrashReports: string[]; memoryUsageBytes: number | null; uptimeSecs: number | null }
/**
 * A VS Code theme the user imported, stored as the already-converted anchor
 * profile plus workbench overrides — never the raw VS Code JSON. Mirrors
 * `ThemePreset` in `src/lib/theme/schema.ts`.
 */
export type ImportedTheme = { id: string; name: string; 
/**
 * `"light"` or `"dark"` — the mode the theme was authored for.
 */
mode: string; accent: string; background: string; foreground: string; contrast: number; overrides: Partial<{ [key in string]: string }> | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type PersistedAppState = { leftSidebarVisible: boolean; rightSidebarVisible: boolean; squareCorners: boolean; lastQuickPaneEntry: string | null; recentItems: string[]; onboardingCompleted: boolean }
/**
 * What a registered global shortcut is *for*.
 * 
 * The app registers more than one accelerator with the OS, but the plugin
 * installs a single handler, so the handler needs a way to tell which
 * registration fired. Keying the registry by purpose gives every accelerator
 * a stable identity that survives the user rebinding it.
 */
export type ShortcutPurpose = 
/**
 * Bring the main window forward from anywhere.
 */
"focusMain" | 
/**
 * Show or dismiss the Quick Pane.
 */
"quickPane"
/**
 * One mode slot's stored theme state. Mirrors `ThemeProfile` in
 * `src/lib/theme/schema.ts`; the default anchors mirror
 * `DEFAULT_LIGHT`/`DEFAULT_DARK` in `src/lib/theme/presets.ts`.
 */
export type ThemeProfile = { presetId: string; customized: boolean; accent: string; background: string; foreground: string; contrast: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
