// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async loadAppState() : Promise<Result<PersistedAppState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_app_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveAppState(appState: PersistedAppState) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_app_state", { appState }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setHasUnsavedChanges(dirty: boolean) : Promise<void> {
    await TAURI_INVOKE("set_has_unsaved_changes", { dirty });
},
async hasUnsavedChanges() : Promise<boolean> {
    return await TAURI_INVOKE("has_unsaved_changes");
},
async logFrontendError(message: string, stack: string | null, componentStack: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_frontend_error", { message, stack, componentStack }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasRecentCrash() : Promise<Result<CrashReportSummary | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_recent_crash") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCrashReports() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_crash_reports") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCrashReport(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_crash_report", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearCrashReports() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_crash_reports") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async collectDiagnostics(tauriVersion: string) : Promise<Result<DiagnosticsReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collect_diagnostics", { tauriVersion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEntitlements() : Promise<FeatureEntitlement[]> {
    return await TAURI_INVOKE("get_entitlements");
},
async setEntitlement(feature: ProFeature, enabled: boolean) : Promise<Result<FeatureEntitlement[], CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_entitlement", { feature, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Registers `accelerator` for `purpose`, replacing whatever that purpose had
 * registered before. No-ops when the accelerator is already the current one.
 */
async registerGlobalShortcut(purpose: ShortcutPurpose, accelerator: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_global_shortcut", { purpose, accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Releases the accelerator held for `purpose`, if any.
 */
async unregisterGlobalShortcut(purpose: ShortcutPurpose) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unregister_global_shortcut", { purpose }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isGlobalShortcutRegistered(accelerator: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_global_shortcut_registered", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Quits for real, whatever the platform's close convention is.
 * 
 * On macOS the main window's close button only hides, so the Quit menu item
 * and the `app-quit` command need a path that actually ends the process. The
 * frontend flushes its stores before calling this.
 */
async quitApp() : Promise<void> {
    await TAURI_INVOKE("quit_app");
},
async getNetworkStatus() : Promise<NetPolicy> {
    return await TAURI_INVOKE("get_network_status");
},
async setOfflineMode(offline: boolean) : Promise<Result<NetPolicy, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_offline_mode", { offline }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAllowLocalhost(allow: boolean) : Promise<Result<NetPolicy, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_allow_localhost", { allow }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every request attempt since launch, newest first.
 */
async listNetworkActivity() : Promise<RequestRecord[]> {
    return await TAURI_INVOKE("list_network_activity");
},
async clearNetworkActivity() : Promise<void> {
    await TAURI_INVOKE("clear_network_activity");
},
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openPreferencesFile() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_preferences_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Positions the pane on whichever monitor the cursor is on, then shows it.
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hides the pane.
 * 
 * Both the blur handler and the submit handler call this, and on some
 * platforms hiding triggers another blur, so the visibility guard keeps the
 * double call harmless.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cleanupOldRecoveryFiles() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Async so the first enumeration (~100ms of directory walking) never blocks
 * the main thread; later calls return the cached list.
 */
async listSystemFonts() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_system_fonts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reads a user-picked VS Code theme file for the import flow.
 * 
 * The frontend does not use `tauri-plugin-fs`, so this one narrow command
 * stands in for it: extension-pinned to theme JSON, size-capped, contents
 * returned as text for the frontend's JSONC parser to make sense of.
 */
async readThemeFile(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_theme_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkForUpdate() : Promise<Result<UpdateInfo | null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Downloads and installs the pending update, then restarts the app. Only
 * returns on failure.
 */
async installUpdate() : Promise<Result<null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Registered vaults, most recently opened first.
 */
async vaultList() : Promise<Result<VaultInfo[], CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultCurrent() : Promise<Result<VaultInfo | null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_current") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates `parent_dir/name` (`AlreadyExists` if it is non-empty),
 * initialises it as a vault and opens it.
 */
async vaultCreate(parentDir: string, name: string, encryption: DbEncryption) : Promise<Result<VaultInfo, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_create", { parentDir, name, encryption }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens an existing folder as a vault, creating `.ostralith/` if missing,
 * registering it and closing the previous vault.
 */
async vaultOpen(path: string) : Promise<Result<VaultInfo, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_open", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * `NotFound` if the id is unknown or its folder is gone.
 */
async vaultOpenById(id: string) : Promise<Result<VaultInfo, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_open_by_id", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultClose() : Promise<Result<null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_close") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes a vault from the registry. Never deletes files.
 */
async vaultForget(id: string) : Promise<Result<null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_forget", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The root's children. Hides `.ostralith`, `.git`, `.trash` and dotfiles.
 */
async listTree() : Promise<Result<TreeNode[], CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tree") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readNote(path: string) : Promise<Result<Note, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_note", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Atomic write. `Conflict` if the file's current hash differs from
 * `expected_hash` (skip the check with `None`).
 */
async writeNote(path: string, content: string, expectedHash: string | null) : Promise<Result<WriteResult, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_note", { path, content, expectedHash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates `Untitled.md` (then `Untitled 1.md`, ...) in `folder` (the root
 * when `None`), or `<title>.md` with `# <title>\n\n` when a title is given.
 */
async createNote(folder: string | null, title: string | null) : Promise<Result<NoteRef, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_note", { folder, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(path: string) : Promise<Result<null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Renames a note or folder and rewrites inbound `[[links]]` in other notes.
 */
async renamePath(from: string, to: string) : Promise<Result<RenameResult, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_path", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Moves into `<vault>/.trash/` under a unique name. Never hard-deletes.
 */
async trashPath(path: string) : Promise<Result<null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trash_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBacklinks(path: string) : Promise<Result<Backlink[], CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_backlinks", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Parses the passed (possibly unsaved) text, not the file on disk.
 */
async getOutline(content: string) : Promise<Result<Heading[], CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_outline", { content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Obsidian rules: exact path, then basename (case-insensitive), shortest
 * path wins. `target` may carry `#heading` and `|alias`.
 */
async resolveLink(fromPath: string, target: string) : Promise<Result<LinkTarget, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_link", { fromPath, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fuzzy match over title and path. An empty query lists the most recently
 * modified notes.
 */
async quickOpen(query: string, limit: number) : Promise<Result<QuickOpenItem[], CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("quick_open", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Full-text search. Supports quoted phrases, `tag:x` and `path:x`.
 */
async searchFulltext(query: string, limit: number) : Promise<Result<SearchHit[], CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_fulltext", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async indexStatus() : Promise<Result<IndexStatus, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("index_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts a full rebuild in the background; progress arrives as
 * [`INDEX_STATUS_EVENT`].
 */
async reindex() : Promise<Result<null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reindex") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dbStatus() : Promise<Result<DbStatus, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async backupStatus() : Promise<Result<BackupStatus, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * `git init` in the vault plus a `.gitignore` for caches, `.trash` and
 * recorded audio.
 */
async backupInit() : Promise<Result<BackupStatus, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_init") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Commits every change. `None` when there was nothing to commit.
 */
async backupNow(message: string | null) : Promise<Result<SnapshotInfo | null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_now", { message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async backupSetRemote(url: string | null) : Promise<Result<BackupStatus, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_set_remote", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Snapshots touching `path`, newest first.
 */
async noteHistory(path: string, limit: number) : Promise<Result<SnapshotInfo[], CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("note_history", { path, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes the note's content at `snapshot_id` as a new change (taking a
 * snapshot of the current state first).
 */
async noteRestore(path: string, snapshotId: string) : Promise<Result<WriteResult, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("note_restore", { path, snapshotId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/

export const EVENTS = {"indexStatus":"index:status","vaultCurrentChanged":"vault:current-changed","vaultFsChanged":"vault:fs-changed"} as const;

/** user-defined types **/

export type AppPreferences = { 
/**
 * See [`CURRENT_PREFS_VERSION`]. The field-level `default` is
 * deliberate: it overrides the container default (which would say
 * "current") so a file without the field reads as 0.
 */
prefsVersion?: number; theme: string; lightProfile: ThemeProfile; darkProfile: ThemeProfile; importedThemes: ImportedTheme[]; 
/**
 * UI font family; `None` means the platform's system font stack.
 */
fontFamily: string | null; 
/**
 * Root font size in px. Rem-based sizing scales with it, so this acts
 * as an overall UI scale rather than a text-only size.
 */
fontSize: number; 
/**
 * `"system"`, `"on"`, or `"off"`.
 */
reducedMotion: string; 
/**
 * Web-style hand cursor over interactive elements instead of the
 * platform-native arrow.
 */
pointerCursors: boolean; 
/**
 * Native window translucency (Mica/Acrylic on Windows, vibrancy on
 * macOS) behind the app canvas. No effect on Linux.
 */
windowEffects: boolean; language: string | null; globalShortcut: string | null; quickPaneShortcut: string | null; 
/**
 * Per-command overrides for in-app shortcuts, keyed by command id.
 * A missing key means "use the command's built-in default"; an explicit
 * `None` means the user unbound the shortcut. Values are normalised
 * frontend combos (e.g. `"mod+shift+k"`), not Tauri accelerators.
 */
commandShortcuts: Partial<{ [key in string]: string | null }> }
export type Backlink = { sourcePath: string; sourceTitle: string; 
/**
 * 0-based line of the link in the source note.
 */
line: number; 
/**
 * That line, trimmed, at most 300 chars.
 */
context: string }
export type BackupStatus = { 
/**
 * Whether the vault is a git repository yet.
 */
initialized: boolean; 
/**
 * Files with changes since the last snapshot.
 */
changedFiles: number; lastSnapshot: SnapshotInfo | null; remote: string | null; 
/**
 * Snapshots not yet pushed to `remote`.
 */
ahead: number }
/**
 * The error every Ostralith command can return.
 * 
 * Serialised with a `kind` tag so the frontend can branch on the variant
 * (show an upgrade hint for `notEntitled`, an offline badge for `offline`)
 * instead of pattern-matching message strings.
 */
export type CoreError = 
/**
 * The feature exists but can't run here: wrong OS, missing hardware,
 * safe mode, or a plugin that is switched off.
 */
{ kind: "featureDisabled"; feature: string; reason: string } | 
/**
 * A Pro feature whose local flag is off.
 */
{ kind: "notEntitled"; feature: ProFeature } | 
/**
 * A request to a non-loopback host while offline mode is on.
 */
{ kind: "offline"; host: string } | 
/**
 * Online, but the host is not on the network allowlist.
 */
{ kind: "hostNotAllowed"; host: string } | 
/**
 * A request that passed the policy but failed on the wire.
 */
{ kind: "network"; message: string } | 
/**
 * Input the command refuses to act on.
 */
{ kind: "invalidInput"; message: string } | 
/**
 * A vault entry, vault, snapshot or other named thing that does not
 * exist. `what` is a human-readable name, usually a vault-relative path.
 */
{ kind: "notFound"; what: string } | 
/**
 * A write whose `expected_hash` no longer matches the file on disk:
 * something else changed it since the editor loaded it.
 */
{ kind: "conflict"; path: string } | 
/**
 * A vault command ran while no vault is open.
 */
{ kind: "noVault" } | 
/**
 * A path that escapes the vault root (`..`, absolute, or via a symlink).
 */
{ kind: "pathOutsideVault"; path: string } | 
/**
 * A create or rename whose destination is already taken.
 */
{ kind: "alreadyExists"; path: string } | 
/**
 * Anything else, carried as a message. Existing `Result<_, String>`
 * helpers convert into this so they can be reused unchanged.
 */
{ kind: "internal"; message: string }
export type CrashReportSummary = { filename: string; timestampSecs: number; secondsAgo: number }
/**
 * How the per-vault SQLite cache is encrypted at rest.
 */
export type DbEncryption = 
/**
 * Plain SQLite.
 */
"none" | 
/**
 * SQLCipher with a key held in the OS keychain.
 */
"keychain"
export type DbStatus = { encryption: DbEncryption; sizeBytes: number; schemaVersion: number; noteCount: number; integrityOk: boolean }
export type DiagnosticsReport = { appName: string; appVersion: string; osName: string; osArch: string; osVersion: string; tauriVersion: string; settings: JsonValue; recentCrashReports: string[]; memoryUsageBytes: number | null; uptimeSecs: number | null }
/**
 * One row of the Pro features list the settings UI renders.
 */
export type FeatureEntitlement = { feature: ProFeature; enabled: boolean }
export type FsChange = { path: string; kind: FsChangeKind; 
/**
 * Set for `Renamed`.
 */
oldPath: string | null }
export type FsChangeKind = "created" | "modified" | "removed" | "renamed"
/**
 * Payload of [`VAULT_FS_CHANGED_EVENT`].
 */
export type FsChangedPayload = { changes: FsChange[] }
export type Heading = { 
/**
 * 1–6.
 */
level: number; text: string; 
/**
 * 0-based line.
 */
line: number; slug: string }
/**
 * A VS Code theme the user imported, stored as the already-converted anchor
 * profile plus workbench overrides — never the raw VS Code JSON. Mirrors
 * `ThemePreset` in `src/lib/theme/schema.ts`.
 */
export type ImportedTheme = { id: string; name: string; 
/**
 * `"light"` or `"dark"` — the mode the theme was authored for.
 */
mode: string; accent: string; background: string; foreground: string; contrast: number; overrides: Partial<{ [key in string]: string }> | null }
export type IndexStatus = { indexing: boolean; done: number; total: number; noteCount: number }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * What a `[[wikilink]]` target resolves to.
 */
export type LinkTarget = { 
/**
 * The target as written (may include `#heading` and `|alias`).
 */
raw: string; 
/**
 * The resolved vault-relative path; for an unresolved link, the path a
 * new note would be created at.
 */
path: string | null; heading: string | null; exists: boolean }
/**
 * What the app may reach, persisted as `network.json`.
 */
export type NetPolicy = { 
/**
 * Block every non-loopback request. On by default: a fresh install
 * makes zero network calls until the user opts in (for example, to
 * download a model).
 */
offline: boolean; 
/**
 * Let loopback requests through even when offline. Local model servers
 * (MLX, llama-server, Ollama, LM Studio) live on 127.0.0.1, so turning
 * this off disables them.
 */
allowLocalhost: boolean; 
/**
 * Hosts reachable while online. An entry is an exact host
 * (`huggingface.co`), a subdomain wildcard (`*.hf.co`, which does not
 * match `hf.co` itself), or `*` for any host.
 */
allowedHosts: string[] }
/**
 * A note as read from disk.
 */
export type Note = { path: string; 
/**
 * Display title as derived by the parser; the file stem when the note
 * has nothing better.
 */
title: string; 
/**
 * The full file content, frontmatter included.
 */
content: string; 
/**
 * Parsed YAML frontmatter, if any.
 */
frontmatter: JsonValue | null; mtime: number; 
/**
 * blake3 hex of `content`; pass it back as `expected_hash` on write.
 */
hash: string }
export type NoteRef = { path: string; title: string }
export type PersistedAppState = { leftSidebarVisible: boolean; rightSidebarVisible: boolean; squareCorners: boolean; lastQuickPaneEntry: string | null; recentItems: string[]; onboardingCompleted: boolean; 
/**
 * Workspace tabs, in strip order. Restored on the next launch. A
 * pre-tabs `state.json` loads with none via the container-level
 * `default` (no field-level one, so the TS type stays non-optional).
 */
openTabs: PersistedTab[]; 
/**
 * `id` of the focused tab in `open_tabs`, if any.
 */
activeTabId: string | null; 
/**
 * Registry id of the vault open at quit; reopened on the next launch.
 */
lastVaultId: string | null }
/**
 * One workspace tab as saved in `state.json`. Mirrors `sanitizeTab` in
 * `src/lib/stores/app-state-schema.ts`.
 */
export type PersistedTab = { id: string; 
/**
 * What the tab shows (`"note"`, `"pdf"`, `"settings"`, ...). Free-form
 * here; the frontend owns the vocabulary.
 */
kind: string; uri: string; title: string; pinned: boolean }
/**
 * A feature that sits behind the Pro flag.
 * 
 * Entitlements are local feature flags only: there is no licence server and
 * no network check. Adding a variant here is the whole of gating a new
 * feature; call [`Entitlements::require`] at the top of its command.
 */
export type ProFeature = 
/**
 * Live translation of a transcript while it is being recorded.
 */
"realtimeTranslation" | 
/**
 * Asking questions of a PDF, answered with page citations.
 */
"pdfAiQa" | 
/**
 * Cloud summaries and research on premium hosted models.
 */
"premiumCloudModels"
export type QuickOpenItem = { path: string; title: string; score: number; titleParts: TextPart[]; pathParts: TextPart[] }
export type RenameResult = { 
/**
 * The new vault-relative path.
 */
path: string; 
/**
 * Number of `[[links]]` rewritten across the vault.
 */
updatedLinks: number; 
/**
 * Number of other notes those links lived in.
 */
updatedFiles: number }
export type RequestOutcome = 
/**
 * Passed the policy and was sent (it may still have failed on the wire;
 * see `error`).
 */
"sent" | 
/**
 * Stopped by the policy before any IO.
 */
"blocked"
/**
 * One entry of the network activity log.
 */
export type RequestRecord = { 
/**
 * Milliseconds since the Unix epoch. `f64` rather than `u64` so the
 * TypeScript side gets a plain `number`.
 */
timestampMs: number; method: string; host: string; 
/**
 * Scheme, host, port and path. Query strings and fragments are dropped
 * because they routinely carry tokens.
 */
url: string; 
/**
 * Why the request was made, e.g. `model-download` or `updater`.
 */
purpose: string; outcome: RequestOutcome; status: number | null; 
/**
 * The response's declared `Content-Length`, when it has one.
 */
bytes: number | null; error: string | null }
export type SearchHit = { path: string; title: string; score: number; snippet: TextPart[] }
/**
 * What a registered global shortcut is *for*.
 * 
 * The app registers more than one accelerator with the OS, but the plugin
 * installs a single handler, so the handler needs a way to tell which
 * registration fired. Keying the registry by purpose gives every accelerator
 * a stable identity that survives the user rebinding it.
 */
export type ShortcutPurpose = 
/**
 * Bring the main window forward from anywhere.
 */
"focusMain" | 
/**
 * Show or dismiss the Quick Pane.
 */
"quickPane"
export type SnapshotInfo = { 
/**
 * The commit sha.
 */
id: string; message: string; 
/**
 * Milliseconds since the Unix epoch.
 */
time: number; filesChanged: number }
/**
 * A run of display text, highlighted or not. Pre-split in Rust so the UI
 * never has to map byte or UTF-16 offsets.
 */
export type TextPart = { text: string; highlight: boolean }
/**
 * One mode slot's stored theme state. Mirrors `ThemeProfile` in
 * `src/lib/theme/schema.ts`; the default anchors mirror
 * `DEFAULT_LIGHT`/`DEFAULT_DARK` in `src/lib/theme/presets.ts`.
 */
export type ThemeProfile = { presetId: string; customized: boolean; accent: string; background: string; foreground: string; contrast: number }
/**
 * One entry of the file tree.
 */
export type TreeNode = { 
/**
 * Vault-relative path.
 */
path: string; 
/**
 * File or folder name, extension included.
 */
name: string; kind: TreeNodeKind; 
/**
 * Milliseconds since the Unix epoch.
 */
mtime: number; 
/**
 * Empty unless `kind` is `Folder`. Folders first, then case-insensitive
 * natural name order.
 */
children: TreeNode[] }
export type TreeNodeKind = "folder" | 
/**
 * A `*.md` file.
 */
"note" | 
/**
 * Any other file shown in the tree.
 */
"file"
export type UpdateInfo = { version: string; currentVersion: string; notes: string | null }
/**
 * A vault in the registry (`$APPDATA/vaults.json`).
 */
export type VaultInfo = { 
/**
 * The uuid from `<vault>/.ostralith/vault.json`.
 */
id: string; name: string; 
/**
 * Absolute path of the vault folder.
 */
path: string; encryption: DbEncryption; 
/**
 * Milliseconds since the Unix epoch.
 */
lastOpenedAt: number }
export type WriteResult = { path: string; mtime: number; hash: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
