export {
  commands,
  EVENTS,
  type Result,
  type AppPreferences,
  type CrashReportSummary,
  type DiagnosticsReport,
  type ImportedTheme,
  type ThemeProfile,
  type PersistedAppState,
  type ShortcutPurpose,
  type JsonValue,
  type NetPolicy,
  type RequestRecord,
  type RequestOutcome,
  type CoreError,
  type ProFeature,
  type FeatureEntitlement,
  type UpdateInfo,
  type PersistedTab,
  // P1: vault, search, db, backup
  type DbEncryption,
  type VaultInfo,
  type TreeNodeKind,
  type TreeNode,
  type Note,
  type WriteResult,
  type NoteRef,
  type RenameResult,
  type Backlink,
  type Heading,
  type LinkTarget,
  type TextPart,
  type QuickOpenItem,
  type SearchHit,
  type IndexStatus,
  type DbStatus,
  type SnapshotInfo,
  type BackupStatus,
  type FsChangeKind,
  type FsChange,
  type FsChangedPayload,
} from './bindings'

export function unwrapResult<T, E>(
  result: { status: 'ok'; data: T } | { status: 'error'; error: E },
): T {
  if (result.status === 'ok') return result.data
  throw result.error
}
