use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{demo, lifecycle, preferences};

    Builder::<tauri::Wry>::new().commands(collect_commands![
        demo::greet,
        lifecycle::confirm_close,
        preferences::load_preferences,
        preferences::save_preferences,
        preferences::open_preferences_file,
    ])
}

pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
