use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{
        app_state, demo, global_shortcut, lifecycle, preferences, quick_pane, recovery,
        theme_import,
    };

    Builder::<tauri::Wry>::new().commands(collect_commands![
        app_state::load_app_state,
        app_state::save_app_state,
        demo::greet,
        global_shortcut::register_global_shortcut,
        global_shortcut::unregister_global_shortcut,
        global_shortcut::is_global_shortcut_registered,
        lifecycle::quit_app,
        preferences::load_preferences,
        preferences::save_preferences,
        preferences::open_preferences_file,
        quick_pane::show_quick_pane,
        quick_pane::dismiss_quick_pane,
        quick_pane::toggle_quick_pane,
        recovery::save_emergency_data,
        recovery::cleanup_old_recovery_files,
        theme_import::read_theme_file,
    ])
}

pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
